apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-store-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::315836106554:role/my-role-aws-eks-secret-csi-demo

